---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  annotations:
    flux.weave.works/tag.podinfo: glob:*
    flux.weave.works/automated: 'true'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.2.0
        ports:
        - containerPort: 9898
